Cleanup

diff --git a/image/entrypoint b/image/entrypoint
--- a/image/entrypoint
+++ b/image/entrypoint
@@ -18,23 +18,30 @@ if [[ -n "$PULSE_COOKIE_DATA" ]]; then
     echo -ne $(echo $PULSE_COOKIE_DATA | sed -e 's/../\\x&/g') >"$PULSE_COOKIE"
 fi
 
-case "$1" in
-    -*)
-        # If we're just given options, prefix mopidy
-        set -- mopidy "$@"
-        ;;
-    host)
-        file=$(basename "$2")
-        case "${file,,}" in
-            *compose*)        file=docker-compose.yml ;;
-            *readme*|*help*)  file=README.md ;;
-        esac
-        file="$APP_HOME/host/$file"
-        exec cat "$file"
-        ;;
-    compose|readme|run)
-        exec "$0" host "$@"
-        ;;
-esac
+main() {
+	case "$1" in
+		-*)
+			# If we're just given options, prefix mopidy
+			set -- mopidy "$@"
+			;;
+		host)
+			file=$(basename "$2")
+			case "${file,,}" in
+				*compose*)        file=docker-compose.yml ;;
+				*readme*|*help*)  file=README.md ;;
+			esac
 
-exec "$@"
+			file="$APP_HOME/host/$file"
+
+			if [[ ! -f "$file" ]]; then
+				echo "File $file not found." >&2
+				exit 1
+			fi
+
+			set -- cat "$file"
+			;;
+	esac
+	exec "$@"
+}
+
+main "$@"
